<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class OfficialsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('officials')->insert([
            // Barangay Captain
            [
                'barangay' => 'Punta',
                'full_name' => 'Juan Dela Cruz',
                'gender' => 'Male',
                'position' => 'Barangay Captain',
                'committee' => null,
                'address' => 'Punta, Cebu City',
                'contact_number' => '09123456789',
                'email' => 'captain.punta@example.com',
                'term_start' => Carbon::parse('2023-01-01'),
                'term_end' => Carbon::parse('2026-12-31'),
                'status' => 'active',
                'photo' => null,
                'remarks' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Kagawads (7)
            [
                'barangay' => 'Punta',
                'full_name' => 'Maria Santos',
                'gender' => 'Female',
                'position' => 'Kagawad',
                'committee' => 'Peace and Order',
                'address' => 'Punta, Cebu City',
                'contact_number' => '09123456780',
                'email' => 'maria.santos@example.com',
                'term_start' => Carbon::parse('2023-01-01'),
                'term_end' => Carbon::parse('2026-12-31'),
                'status' => 'active',
                'photo' => null,
                'remarks' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'barangay' => 'Punta',
                'full_name' => 'Pedro Reyes',
                'gender' => 'Male',
                'position' => 'Kagawad',
                'committee' => 'Health',
                'address' => 'Punta, Cebu City',
                'contact_number' => '09123456781',
                'email' => 'pedro.reyes@example.com',
                'term_start' => Carbon::parse('2023-01-01'),
                'term_end' => Carbon::parse('2026-12-31'),
                'status' => 'active',
                'photo' => null,
                'remarks' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'barangay' => 'Punta',
                'full_name' => 'Ana Lopez',
                'gender' => 'Female',
                'position' => 'Kagawad',
                'committee' => 'Education',
                'address' => 'Punta, Cebu City',
                'contact_number' => '09123456782',
                'email' => 'ana.lopez@example.com',
                'term_start' => Carbon::parse('2023-01-01'),
                'term_end' => Carbon::parse('2026-12-31'),
                'status' => 'active',
                'photo' => null,
                'remarks' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'barangay' => 'Punta',
                'full_name' => 'Jose Lim',
                'gender' => 'Male',
                'position' => 'Kagawad',
                'committee' => 'Infrastructure',
                'address' => 'Punta, Cebu City',
                'contact_number' => '09123456783',
                'email' => 'jose.lim@example.com',
                'term_start' => Carbon::parse('2023-01-01'),
                'term_end' => Carbon::parse('2026-12-31'),
                'status' => 'active',
                'photo' => null,
                'remarks' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'barangay' => 'Punta',
                'full_name' => 'Elena Garcia',
                'gender' => 'Female',
                'position' => 'Kagawad',
                'committee' => 'Social Services',
                'address' => 'Punta, Cebu City',
                'contact_number' => '09123456784',
                'email' => 'elena.garcia@example.com',
                'term_start' => Carbon::parse('2023-01-01'),
                'term_end' => Carbon::parse('2026-12-31'),
                'status' => 'active',
                'photo' => null,
                'remarks' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'barangay' => 'Punta',
                'full_name' => 'Mark Cruz',
                'gender' => 'Male',
                'position' => 'Kagawad',
                'committee' => 'Environment',
                'address' => 'Punta, Cebu City',
                'contact_number' => '09123456785',
                'email' => 'mark.cruz@example.com',
                'term_start' => Carbon::parse('2023-01-01'),
                'term_end' => Carbon::parse('2026-12-31'),
                'status' => 'active',
                'photo' => null,
                'remarks' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'barangay' => 'Punta',
                'full_name' => 'Rosa Bautista',
                'gender' => 'Female',
                'position' => 'Kagawad',
                'committee' => 'Budget & Finance',
                'address' => 'Punta, Cebu City',
                'contact_number' => '09123456786',
                'email' => 'rosa.bautista@example.com',
                'term_start' => Carbon::parse('2023-01-01'),
                'term_end' => Carbon::parse('2026-12-31'),
                'status' => 'active',
                'photo' => null,
                'remarks' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // SK Chairperson
            [
                'barangay' => 'Punta',
                'full_name' => 'Kevin Flores',
                'gender' => 'Male',
                'position' => 'SK Chairperson',
                'committee' => 'Youth Development',
                'address' => 'Punta, Cebu City',
                'contact_number' => '09123456787',
                'email' => 'kevin.flores@example.com',
                'term_start' => Carbon::parse('2023-01-01'),
                'term_end' => Carbon::parse('2026-12-31'),
                'status' => 'active',
                'photo' => null,
                'remarks' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
